#!/bin/sh
set -e

# Reload udev rules
udevadm control --reload-rules || true
udevadm trigger || true

# Reload systemd
systemctl daemon-reload || true

# Enable and start service on fresh install
if [ "$1" = "configure" ]; then
    systemctl enable af-pro-display.service || true
    systemctl start af-pro-display.service || true
fi


#DEBHELPER#